import stream from 'stream';

export default class TransformScript extends stream.Transform {
  private hasInserted: boolean = false;

  constructor(private deviceIds: ReadonlyArray<string>) {
    super();
  }

  public _transform(data, _, cb): void {
    const insertion = '' +
      '/**\n' +
      ' * @supported ' + `${this.deviceIds.join(' ')}` + '\n' +
      ' * THIS COMMENT IS GENERATED BY SURGIO\n' +
      ' */\n\n';

    if (!this.hasInserted) {
      this.push(insertion);
      this.hasInserted = true;
    }

    this.push(data);
    cb();
  }
}
