import path from 'node:path'
import { pathToFileURL } from 'node:url'
import fs from 'fs-extra'
import nunjucks from 'nunjucks'

import packageJson from '../../package.json' with { type: 'json' }
import { defineSurgioProject } from '../project/core.js'
import { resolveSurgioProjectFile } from '../project/file.js'
import { projectToRuntimeProjection } from '../project/internal.js'

import { normalizeWorkerConfig } from './normalize-config.js'

import type {
  WorkerCompiledTemplate,
  WorkerProjectDefinition,
} from './types.js'

export interface BuildWorkerManifestOptions {
  readonly configFile?: string
  readonly outfile?: string
}

const toPosix = (value: string): string => value.split(path.sep).join('/')

const listFiles = async (directory: string): Promise<string[]> => {
  const entries = await fs.readdir(directory, { withFileTypes: true })
  const files = await Promise.all(
    entries.map(async (entry) => {
      const absolute = path.join(directory, entry.name)
      return entry.isDirectory() ? listFiles(absolute) : [absolute]
    }),
  )
  return files.flat()
}

const compileTemplate = (name: string, source: string): string =>
  nunjucks.precompileString(source, {
    name,
    wrapper(templates) {
      const template = Array.isArray(templates) ? templates[0] : templates
      return `(function () {\n${template.template}\n})()`
    },
  })

const validateProjectReferences = (
  configInput: import('../project/types.js').SurgioProjectConfig,
  providerDefinitions: WorkerProjectDefinition['providers'],
  templateNames: ReadonlySet<string>,
  jsonTemplateNames: ReadonlySet<string>,
): void => {
  const providers = new Set(Object.keys(providerDefinitions))
  for (const artifact of normalizeWorkerConfig(configInput).artifacts) {
    for (const provider of [
      artifact.provider,
      ...(artifact.combineProviders ?? []),
    ]) {
      if (!providers.has(provider)) {
        throw new Error(
          `Artifact ${artifact.name} 引用了未注册的 Provider ${provider}`,
        )
      }
    }
    if (artifact.templateString) {
      continue
    }
    const templateName = `${artifact.template}.${
      artifact.templateType === 'json' ? 'json' : 'tpl'
    }`
    const available =
      artifact.templateType === 'json' ? jsonTemplateNames : templateNames
    if (!available.has(templateName)) {
      throw new Error(`Artifact ${artifact.name} 的模板 ${templateName} 不存在`)
    }
  }
}

export const buildWorkerManifest = async (
  options: BuildWorkerManifestOptions = {},
): Promise<{ readonly outfile: string }> => {
  const configFile = options.configFile
    ? path.resolve(options.configFile)
    : resolveSurgioProjectFile(process.cwd(), { required: true })!
  if (!/\.(?:ts|mts|mjs|js)$/.test(configFile)) {
    throw new Error('Worker 配置必须是 ESM .ts、.mts、.mjs 或 .js 文件')
  }
  const outfile = path.resolve(options.outfile ?? '.surgio/worker-manifest.mjs')
  const imported = await import(
    `${pathToFileURL(configFile).href}?surgio=${Date.now()}`
  )
  const project = defineSurgioProject(
    imported.default as WorkerProjectDefinition,
  )
  const projection = projectToRuntimeProjection(project)
  const buildConfig = projection.config
  normalizeWorkerConfig(buildConfig)

  const templateDir = path.resolve(
    path.dirname(configFile),
    projection.templateDir ?? './template',
  )
  if (!(await fs.pathExists(templateDir))) {
    throw new Error(`模板目录 ${templateDir} 不存在`)
  }

  const templates: Record<string, string> = {}
  const rawTemplates: Record<string, string> = {}
  const jsonTemplates: Record<string, unknown> = {}
  for (const filename of await listFiles(templateDir)) {
    const name = toPosix(path.relative(templateDir, filename))
    if (name.endsWith('.tpl')) {
      const source = await fs.readFile(filename, 'utf8')
      rawTemplates[name] = source
      templates[name] = compileTemplate(name, source)
    } else if (name.endsWith('.json')) {
      jsonTemplates[name] = await fs.readJson(filename)
    }
  }

  const artifactTemplates: Record<string, string> = {}
  for (const artifact of normalizeWorkerConfig(buildConfig).artifacts) {
    if (artifact.templateString) {
      const name = `__artifacts__/${artifact.name}.tpl`
      templates[name] = compileTemplate(name, artifact.templateString)
      rawTemplates[name] = artifact.templateString
      artifactTemplates[artifact.name] = name
    }
  }
  validateProjectReferences(
    projection.config,
    projection.providers,
    new Set(Object.keys(templates)),
    new Set(Object.keys(jsonTemplates)),
  )

  const relativeConfig = toPosix(
    path.relative(path.dirname(outfile), configFile),
  )
  const importPath = relativeConfig.startsWith('.')
    ? relativeConfig
    : `./${relativeConfig}`
  const compiledEntries = Object.entries(templates)
    .map(([name, body]) => `${JSON.stringify(name)}: ${body}`)
    .join(',\n')
  const output =
    `// Generated by surgio/worker/build. Do not edit.\n` +
    `import project from ${JSON.stringify(importPath)};\n` +
    `const { providers, templateDir: _templateDir, ...projectConfig } = project;\n` +
    `const config = {\n` +
    `  ...projectConfig,\n` +
    `  artifacts: projectConfig.artifacts.map(({ destDir, destDirs, ...artifact }) => artifact)\n` +
    `};\n` +
    `const templates = {\n${compiledEntries}\n};\n` +
    `const manifest = {\n` +
    `  surgioVersion: ${JSON.stringify(packageJson.version)},\n` +
    `  config,\n` +
    `  providers,\n` +
    `  templates,\n` +
    `  rawTemplates: ${JSON.stringify(rawTemplates)},\n` +
    `  jsonTemplates: ${JSON.stringify(jsonTemplates)},\n` +
    `  artifactTemplates: ${JSON.stringify(artifactTemplates)}\n` +
    `};\nexport default manifest;\n`

  await fs.ensureDir(path.dirname(outfile))
  await fs.writeFile(outfile, output, 'utf8')
  const declarationFile = outfile.replace(/\.mjs$/, '.d.mts')
  if (declarationFile !== outfile) {
    await fs.writeFile(
      declarationFile,
      `declare const manifest: import('surgio/worker').WorkerManifest;\nexport default manifest;\n`,
      'utf8',
    )
  }
  return { outfile }
}

export type { WorkerCompiledTemplate, WorkerProjectDefinition }
