export const ENV_NETWORK_TIMEOUT_KEY = 'SURGIO_NETWORK_TIMEOUT'

export const ENV_NETWORK_RESOLVE_TIMEOUT = 'SURGIO_NETWORK_RESOLVE_TIMEOUT'

export const ENV_SURGIO_NETWORK_CONCURRENCY = 'SURGIO_NETWORK_CONCURRENCY'

export const ENV_SURGIO_NETWORK_RETRY = 'SURGIO_NETWORK_RETRY'

export const ENV_SURGIO_NETWORK_CLASH_UA = 'SURGIO_NETWORK_CLASH_UA'

export const ENV_SURGIO_REMOTE_SNIPPET_CACHE_MAXAGE =
  'SURGIO_REMOTE_SNIPPET_CACHE_MAXAGE'

export const ENV_SURGIO_PROVIDER_CACHE_MAXAGE = 'SURGIO_PROVIDER_CACHE_MAXAGE'

export const ENV_SURGIO_GFW_FREE = 'SURGIO_GFW_FREE'

export const SURGIO_RENDERED_ARTIFACT_CACHE_MAXAGE =
  'SURGIO_RENDERED_ARTIFACT_CACHE_MAXAGE'
